services:
  nsight-profiler:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/azdevops143/nsightprofiling-gpu:latest
    container_name: nsight_heat_diffusion_profiler
    privileged: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./reports:/reports
    command: ["256", "1e-4", "1000"]
